In [5]:
from astropy.table import Table
from astropy.io import ascii
import pandas as pd

In [3]:
yse_meta = pd.read_csv("../csv/yse_not_in_bts_or_tns.csv")

In [4]:
yse_meta.head()

,Object,RA,Dec,Spec. Class,"Redshift, $z$",Prediction,Confidence,p_SNII,p_SNIa,p_SNIbc,IAUID
0,2019lbi,190.088004,1.273998,SNII,0.038,SNIa,0.497,0.278,0.497,0.225,SN2019lbi
1,2019szh,147.176208,-8.734392,SNIa-norm,0.053,SNIa,1.000,0.000,1.000,0.000,SN2019szh
2,2019tvv,177.772596,21.767258,SNIa-norm,0.059,SNIa,1.000,0.000,1.000,0.000,SN2019tvv
3,2019ucc,49.642135,-4.429429,NaN,0.066,SNIbc,0.870,0.005,0.125,0.870,SN2019ucc
4,2019uev,142.706471,30.871843,NaN,0.060,SNIbc,0.779,0.019,0.202,0.779,SN2019uev

In [24]:
filename = "../csv/yse_files/yse_dr1_zenodo_snr_geq_4/2019lbi.snana.dat"

In [56]:
def read_dat_file(fname):
    
    with open(fname) as f:
        lc_dict = {
            "mjd":[],
            "magpsf":[],
            "sigmapsf":[],
            "fid":[]
        }
        
        for line in f:
            if line.startswith('SNID'):
                _snid, snid = line.split()
                
            if not line.startswith('OBS: '):
                continue
            
            _obs, mjd, fid, _field, fluxcal, fluxcalerr, magpsf, sigmapsf, _flag = line.split()
            if fid in ['X', 'Y', 'g', 'r']:
                fid_lasair = "1" if fid in ['X', 'g'] else "2"
                lc_dict["mjd"].append(mjd)
                lc_dict["magpsf"].append(magpsf)
                lc_dict["sigmapsf"].append(sigmapsf)
                lc_dict["fid"].append(fid_lasair)
        
        lc_df = pd.DataFrame(lc_dict)
        lc_df['objId'] = "SN"+snid
        
        return lc_df

In [57]:
read_dat_file(filename)

          mjd  magpsf sigmapsf fid      objId
0   59486.600  20.008    0.107   1  SN2021zzv
1   59492.550  19.739    0.075   2  SN2021zzv
2   59498.600  20.027    0.066   1  SN2021zzv
3   59498.600  19.750    0.054   2  SN2021zzv
4   59501.560  20.118    0.081   1  SN2021zzv
5   59504.600  19.699    0.067   2  SN2021zzv
6   59506.000  19.739    0.078   2  SN2021zzv
7   59513.480  19.772    0.077   2  SN2021zzv
8   59516.530  20.375    0.194   1  SN2021zzv
9   59518.560  20.508    0.170   1  SN2021zzv
10  59524.490  19.774    0.079   2  SN2021zzv
11  59524.500  20.643    0.173   1  SN2021zzv

In [58]:
id_list = yse_meta.Object.to_list()

In [59]:
lcs = []
for objid in id_list:
    try:
        filename = "../csv/yse_files/yse_dr1_zenodo_snr_geq_4/"+objid+".snana.dat"
        lcs.append(read_dat_file(filename))
    except:
        print("error in file "+objid)
        continue

In [60]:
lcs_df = pd.concat(lcs, ignore_index=True)

In [61]:
lcs_df

             mjd  magpsf sigmapsf fid      objId
0      58676.172  17.042    0.018   1  SN2019lbi
1      58676.192  17.116    0.018   2  SN2019lbi
2      58679.187  17.100    0.023   1  SN2019lbi
3      58679.191  17.156    0.023   2  SN2019lbi
4      58797.545  18.021    0.042   2  SN2019lbi
...          ...     ...      ...  ..        ...
44436  59513.480  19.772    0.077   2  SN2021zzv
44437  59516.530  20.375    0.194   1  SN2021zzv
44438  59518.560  20.508    0.170   1  SN2021zzv
44439  59524.490  19.774    0.079   2  SN2021zzv
44440  59524.500  20.643    0.173   1  SN2021zzv

[44441 rows x 5 columns]

In [62]:
len(lcs_df.objId.unique())

1807

In [63]:
lcs_df["magzpsci"] = 27.5
lcs_df["isdiffpos"] = "t"

In [64]:
lcs_df

             mjd  magpsf sigmapsf fid      objId  magzpsci isdiffpos
0      58676.172  17.042    0.018   1  SN2019lbi      27.5         t
1      58676.192  17.116    0.018   2  SN2019lbi      27.5         t
2      58679.187  17.100    0.023   1  SN2019lbi      27.5         t
3      58679.191  17.156    0.023   2  SN2019lbi      27.5         t
4      58797.545  18.021    0.042   2  SN2019lbi      27.5         t
...          ...     ...      ...  ..        ...       ...       ...
44436  59513.480  19.772    0.077   2  SN2021zzv      27.5         t
44437  59516.530  20.375    0.194   1  SN2021zzv      27.5         t
44438  59518.560  20.508    0.170   1  SN2021zzv      27.5         t
44439  59524.490  19.774    0.079   2  SN2021zzv      27.5         t
44440  59524.500  20.643    0.173   1  SN2021zzv      27.5         t

[44441 rows x 7 columns]

In [66]:
lcs_df.to_csv('yse_lcs.csv',index=False)